export const WS_MESSAGE_TYPES = {
  QUEUE_UPDATE: 'QUEUE_UPDATE',
  YOUR_TURN: 'YOUR_TURN',
  POSITION_CHANGED: 'POSITION_CHANGED',
  NO_SHOW: 'NO_SHOW',
  PATIENT_ASSIGNED: 'PATIENT_ASSIGNED',
  ROOM_STATUS_CHANGED: 'ROOM_STATUS_CHANGED',
  QUEUE_STATS: 'QUEUE_STATS',
  DISPLAY_UPDATE: 'DISPLAY_UPDATE',
  HEARTBEAT: 'HEARTBEAT',
} as const;

export type WSMessageType = (typeof WS_MESSAGE_TYPES)[keyof typeof WS_MESSAGE_TYPES];

export const HEARTBEAT_INTERVAL_MS = 30_000;
export const HEARTBEAT_TIMEOUT_MS = 90_000;
export const RECONNECT_BASE_DELAY_MS = 1_000;
export const RECONNECT_MAX_DELAY_MS = 30_000;
